<?php require_once './templates/layout/header.phtml'?>
<div class="list-container">
    <ul>
        <?php foreach($teams as $team): ?>
            <li><?= htmlspecialchars($team->marca) ?> 
            <span class="bold">Temporada</span> <?= htmlspecialchars($team->temporada) ?> 
            <span class="bold">Camiseta</span> <?= htmlspecialchars($team->camiseta) ?>
            <span class="bold">Equipos</span> 
            <?php foreach($equipos as $equipo): ?>
                <?php if($equipo->id_equipo == $team->id_equipo): ?>
                    <?= $equipo->nombre ?>
                <?php endif ?>
            <?php endforeach ?>
            <div class="list-button-container">
                <div class="list-button interactive"><a href="<?= BASE_URL?>teams/team/<?= $team->id ?>">Ver mas</a></div>
                <?php if($this->user && $this->user->rol == 'admin') :?>
                    <div class="list-button interactive"><a href="delete/<?= $team->id?>" type="button">Eliminar</a></div>
                    <div class="list-button interactive"><a href="edit/<?= $team->id ?>" type="button">Editar</a></div>
                <?php endif ?>
            </div>
            
            </li>
        <?php endforeach ?>
    </ul>
</div>