<?php require_once 'templates/layouts/header.phtml';?>

<?php if($error): ?>
    <div class= 'alert alert-danger' role = 'alert'>
        <?= $error?>
    </div>
    <?php endif ?>

<form action="login" method="post">
<div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Nombre de usuario</label>
    <input type="text" class="form-control" id="user" name="user" aria-describedby="emailHelp" required>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="password" name="password" required>
  </div>
  <button type="submit" class="btn btn-primary">Ingresar</button>
</form>
